apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-1
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 4
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: nginx
        ports:
        - containerPort: 8484